1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


Ans- We can create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns (transposing the array). Here's how we can do it:


import numpy as np  

# Create a 3x3 array with random integers between 1 and 100  
array = np.random.randint(1, 101, size=(3, 3))  

# Print the original array  
print("Original Array:")  
print(array)  

# Interchange rows and columns (transpose the array)  
transposed_array = array.T  

# Print the transposed array  
print("\nTransposed Array:")  
print(transposed_array)  

This code uses numpy to generate the random integers and then transposes the array. The .T property of a NumPy array is used to get the transpose of the array, effectively interchanging its rows and columns.




2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.



Ans- We can generate a 1D NumPy array with 10 elements and then reshape it into both a 2x5 array and a 5x2 array using NumPy's reshape function. Here's how we can do it:


import numpy as np  

# Generate a 1D array with 10 elements  
array_1d = np.arange(10)  # This creates an array with values from 0 to 9  

# Print the original 1D array  
print("Original 1D Array:")  
print(array_1d)  

# Reshape it into a 2x5 array  
array_2x5 = array_1d.reshape(2, 5)  

# Print the reshaped 2x5 array  
print("\nReshaped 2x5 Array:")  
print(array_2x5)  

# Reshape it into a 5x2 array  
array_5x2 = array_1d.reshape(5, 2)  

# Print the reshaped 5x2 array  
print("\nReshaped 5x2 Array:")  
print(array_5x2)  

Explanation:

np.arange(10) generates a 1D array with elements from 0 to 9.
The reshape method is used to change the shape of the original 1D array into the specified dimensions (2x5 and 5x2).




3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


Ans- To create a 4x4 NumPy array with random float values and then add a border of zeros around it, we can use NumPy's np.pad function. Here's how we  can do it:


import numpy as np  

# Create a 4x4 array with random float values  
array_4x4 = np.random.rand(4, 4)  

# Print the original 4x4 array  
print("Original 4x4 Array:")  
print(array_4x4)  

# Add a border of zeros around the array  
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)  

# Print the new 6x6 array with a border of zeros  
print("\n6x6 Array with Border of Zeros:")  
print(array_with_border)  

Explanation:

np.random.rand(4, 4) generates a 4x4 array with random float values between 0 and 1.
np.pad is used to add a border of zeros around the array. The pad_width=1 argument specifies that one layer of zeros should be added around the original array. mode='constant' with constant_values=0 sets the value of the padding to zero.
The resulting 6x6 array has the original values in the center and a border of zeros surrounding them.





4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.



Ans- We can create an array of integers from 10 to 60 with a step of 5 using NumPy's np.arange function. Here's how to do it:


import numpy as np  

# Create an array of integers from 10 to 60 with a step of 5  
array_integers = np.arange(10, 61, 5)  

# Print the resulting array  
print("Array of integers from 10 to 60 with a step of 5:")  
print(array_integers)  

Explanation:
np.arange(start, stop, step) is a function that generates values from start to stop (exclusive) with the specified step.

In this case, start is 10, stop is 61 (to include 60), and step is 5. The resulting array will include the integers [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60].




5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.



Ans- We can create a NumPy array of strings and then apply various case transformations such as uppercase, lowercase, title case, and others using NumPy's vectorized string functions. Here's how we can do it:


import numpy as np  

# Create a NumPy array of strings  
string_array = np.array(['python', 'numpy', 'pandas'])  

# Apply different case transformations  
uppercase_array = np.char.upper(string_array)  
lowercase_array = np.char.lower(string_array)  
titlecase_array = np.char.title(string_array)  
capitalize_array = np.char.capitalize(string_array)  

# Print the original and transformed arrays  
print("Original Array:")  
print(string_array)  

print("\nUppercase Array:")  
print(uppercase_array)  

print("\nLowercase Array:")  
print(lowercase_array)  

print("\nTitlecase Array:")  
print(titlecase_array)  

print("\nCapitalized Array:")  
print(capitalize_array)  

Explanation:

np.array(['python', 'numpy', 'pandas']) creates a NumPy array containing the specified strings.
The various transformations are done using np.char.upper(), np.char.lower(), np.char.title(), and np.char.capitalize():
np.char.upper() converts each element to uppercase.
np.char.lower() converts each element to lowercase.
np.char.title() converts the first character of each word to uppercase and the remaining characters to lowercase.
np.char.capitalize() converts the first character of each string to uppercase and the rest to lowercase.

This will give  us  array for each transformation.





6.Generate a NumPy array of words. Insert a space between each character of every word in the array.


Ans- We can generate a NumPy array of words and then insert a space between each character of every word by using NumPy's vectorized string operations. Here's how to do it:


import numpy as np  

# Create a NumPy array of words  
words_array = np.array(['hello', 'world', 'numpy', 'python'])  

# Insert a space between each character of every word  
spaced_words_array = np.char.join(' ', words_array)  

# Print the original and modified arrays  
print("Original Array of Words:")  
print(words_array)  

print("\nArray of Words with Spaces Between Characters:")  
print(spaced_words_array)  

Explanation:

np.array(['hello', 'world', 'numpy', 'python']) creates a NumPy array containing the specified words.

np.char.join(' ', words_array) is used to insert a space between each character of every word in the array. The join function takes the specified string (in this case, a space ' ') and inserts it between the characters of each word.

The output will show the original array of words and the modified array where spaces are inserted between the characters in each word.

Output Example
For the above code, the output would look like this:


Original Array of Words:  
['hello' 'world' 'numpy' 'python']  

Array of Words with Spaces Between Characters:  
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']  




7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.



Ans- We can create two 2D NumPy arrays and perform various element-wise operations such as addition, subtraction, multiplication, and division. Here's an example of how to do this:


import numpy as np  

# Create two 2D NumPy arrays  
array1 = np.array([[1, 2, 3], [4, 5, 6]])  
array2 = np.array([[10, 20, 30], [40, 50, 60]])  

# Perform element-wise addition  
addition_result = array1 + array2  

# Perform element-wise subtraction  
subtraction_result = array1 - array2  

# Perform element-wise multiplication  
multiplication_result = array1 * array2  

# Perform element-wise division  
division_result = array1 / array2  

# Print the results  
print("Array 1:")  
print(array1)  

print("\nArray 2:")  
print(array2)  

print("\nElement-wise Addition:")  
print(addition_result)  

print("\nElement-wise Subtraction:")  
print(subtraction_result)  

print("\nElement-wise Multiplication:")  
print(multiplication_result)  

print("\nElement-wise Division:")  
print(division_result)  

Explanation:

np.array([[1, 2, 3], [4, 5, 6]]) creates a 2D array called array1 with two rows and three columns.
np.array([[10, 20, 30], [40, 50, 60]]) creates another 2D array called array2.

Element-wise operations are performed using standard arithmetic operators:
Addition: array1 + array2
Subtraction: array1 - array2
Multiplication: array1 * array2
Division: array1 / array2

The results of each operation are stored in separate variables and then printed.

Output Example
The output for the code above will look like this:


Array 1:  
[[1 2 3]  
 [4 5 6]]  

Array 2:  
[[10 20 30]  
 [40 50 60]]  

Element-wise Addition:  
[[11 22 33]  
 [44 55 66]]  

Element-wise Subtraction:  
[[ -9 -18 -27]  
 [-36 -45 -54]]  

Element-wise Multiplication:  
[[ 10  40  90]  
 [160 250 360]]  

Element-wise Division:  
[[0.1        0.1        0.1       ]  
 [0.1        0.1        0.1       ]]





8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


Ans- We can easily create a 5x5 identity matrix and extract its diagonal elements using NumPy. Here’s how we can do it:


import numpy as np  

# Create a 5x5 identity matrix  
identity_matrix = np.eye(5)  

# Extract the diagonal elements  
diagonal_elements = np.diag(identity_matrix)  

# Print the results  
print("5x5 Identity Matrix:")  
print(identity_matrix)  

print("\nDiagonal Elements:")  
print(diagonal_elements)  

Explanation:
np.eye(5) creates a 5x5 identity matrix.
np.diag(identity_matrix) extracts the diagonal elements of the matrix.

Output:
When we run the code, we will get the following output:

5x5 Identity Matrix:  
[[1. 0. 0. 0. 0.]  
 [0. 1. 0. 0. 0.]  
 [0. 0. 1. 0. 0.]  
 [0. 0. 0. 1. 0.]  
 [0. 0. 0. 0. 1.]]  

Diagonal Elements:  
[1. 1. 1. 1. 1.]  




9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.



Ans- Here's how we can generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all prime numbers in that array.


import numpy as np  

# Generate an array of 100 random integers between 0 and 1000  
random_integers = np.random.randint(0, 1001, size=100)  

# Function to check if a number is prime  
def is_prime(num):  
     if num < 2:  
        return False  
     for i in range(2, int(num ** 0.5) + 1):  
        if num % i == 0:  
            return False  
     return True  

# Find all prime numbers in the array  
prime_numbers = [num for num in random_integers if is_prime(num)]  

# Display the results  
print("Random Integers Array:")  
print(random_integers)  

print("\nPrime Numbers:")  
print(prime_numbers)  

Explanation of the Code:

Generate Random Integers: The line np.random.randint(0, 1001, size=100) creates an array of 100 random integers in the range from 0 to 1000.

Prime Checking Function: The is_prime function checks if a number is prime:
It returns False for any number less than 2 (not prime).
For numbers 2 or greater, it checks divisibility from 2 to the square root of that number. If a factor is found, it returns False.
If no factors are found, it returns True (the number is prime).

List Comprehension: It uses a list comprehension to create a list of prime numbers by checking each number in the random integers array with the is_prime function.

Display Output: Finally, it prints the random integers and the list of prime numbers.

Output:
When we run the code, we will see output similar to this (actual values will vary due to randomness):

Random Integers Array:  
[543, 290, 29, 117, 962, 3, 442, ...]  # This will show 100 random integers  

Prime Numbers:  
[3, 29, 131, 383, 547, ...]  # This will show all prime numbers found in the array  

The Random Integers Array contains 100 random integers, and the Prime Numbers section lists all the prime integers found in that array.


10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.



Ans- To create a NumPy array representing daily temperatures for a month and calculate the weekly averages, we can follow this example:


import numpy as np  

# Create a NumPy array representing daily temperatures for a month (30 days)  
# Let's generate random temperatures between -10 and 35 degrees Celsius  
daily_temperatures = np.random.uniform(low=-10, high=35, size=30)  

# Calculate the weekly averages  
# Reshape the array into a shape of (4, 7) to represent 4 weeks  
# Each row will represent a week, and each column will represent a day of the week  
weekly_temperatures = daily_temperatures.reshape(4, 7)  

# Calculate the average for each week  
weekly_averages = np.mean(weekly_temperatures, axis=1)  

# Display the daily temperatures and the weekly averages  
print("Daily Temperatures for the Month:")  
print(daily_temperatures)  

print("\nWeekly Averages:")  
print(weekly_averages)  

Explanation:

Generating Daily Temperatures: The np.random.uniform(low=-10, high=35, size=30) function creates an array of 30 random temperatures between -10 and 35 degrees Celsius.

Reshaping the Array: The reshape(4, 7) method reshapes the array into a 4x7 matrix, where each row represents a week.

Calculating Weekly Averages: The np.mean(..., axis=1) function calculates the mean for each row (week), giving the average temperature for that week.

Displaying Results: The code prints both the daily temperature array and the calculated weekly averages.

Output:
When we run the code, it will display the daily temperatures for the month and the corresponding weekly averages. Since the temperatures are generated randomly, the output will vary each time we run the code. Here's an example of what the output might look like:


Daily Temperatures for the Month:  
[12.34  25.67  18.45  ...]  # Example output with 30 values  

Weekly Averages:  
[15.46 20.12 23.67 12.98]  # Example weekly averages for 4 weeks  




